### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by MrBlaze29** [pbzweihander/peace-eye#1]
Blank screen after successfully connecting to my own server. 

![image](https://github.com/pbzweihander/peace-eye/assets/81372082/d132d63d-e778-4e07-a4eb-8f3dd05bd8d1)

**Comment by pbzweihander** [comment]
What was your server's map? Caucasus?

**Comment by pbzweihander** [comment]
Is there any toast about errors?

Strange....

**Comment by MrBlaze29** [comment]
I tried on Caucasus, at first I couldn't event connect due to TCP error so I forwarded the Port and managed to get a connection.
Then after connecting, a message on the server notifications appeared saying that Peace-Eye connected. But instead of a map I got the picture I showed.

Ps. I tried connecting to hogging and everything was fine.

**Comment by pbzweihander** [comment]
Did you use Tacview realtime telemetry server's port, not DCS server's, right?

It is quite strange. You rather see any error or failure to connect. I don't understand why a 'blank' screen appears. Strange......

**Comment by MrBlaze29** [comment]
I'll try to make a dedicated server and create a realtime telemetry instance to record from it. I'll post the results as soon as I get home today.

**Comment by pbzweihander** [comment]
By the way, thanks for the first issue! I'm very happy that someone else is using `peace-eye`. Feel free to add another issue, feature request, etc!

**Comment by MrBlaze29** [comment]
Thank you for making GCI accessible for everyone. My squad and I are very excited about the future of this project and how it can allow people to experience another aspect of air combat.

**Comment by MrBlaze29** [comment]
So far I learned that it must be something about the tacview data because I tested the software in other servers and it worked. I spoke with the admin of one of them and we´ll be doing further testing this weekend. If we solve the issue we´ll probably implement this tool in our future missions.

**Comment by MrBlaze29** [comment]
Problem solved. I created a dedicated server and inside the options.lua file in C:\Users\USER\Saved Games\Server.DCS\Config I manually added 
```
["Tacview"] = 
        {
            ["tacviewExportPath"] = "",
            ["tacviewDebugMode"] = 0,
            ["tacviewRemoteControlPort"] = "42675",
            ["tacviewFlightDataRecordingEnabled"] = true,
            ["tacviewRealTimeTelemetryPassword"] = "",
            ["tacviewSinglePlayerFlights"] = 2,
            ["tacviewTerrainExport"] = 0,
            ["tacviewAutoDiscardFlights"] = 10,
            ["tacviewRemoteControlPassword"] = "",
            ["tacviewRealTimeTelemetryPort"] = "42674",
            ["tacviewMultiplayerFlightsAsHost"] = 2,
            ["tacviewRemoteControlEnabled"] = false,
            ["tacviewRealTimeTelemetryEnabled"] = true,
            ["tacviewBookmarkShortcut"] = 0,
            ["tacviewMultiplayerFlightsAsClient"] = 2,
            ["tacviewModuleEnabled"] = true,
        }, -- end of ["Tacview"]
```
in the plugins section. Make sure that you have the marked parameters like me
After that everything worked like a charm.
