### ISSUE TITLE
Unable to use in Peace-Eye in some missions.

### ISSUE THREAD

**Issue by MrBlaze29** [pbzweihander/peace-eye#2]
For some reason Peace Eye doesn't seem to work in Liberation or Briefing Room missions in a dedicated server. It only appears to work in Foothold.  Further testing will be conducted. In every attempt, it does appear to connect to the server but doesn't display anything (grey screen). It only shows data in the Foothold mission.

References:
Foothold : https://www.digitalcombatsimulator.com/en/files/3319499/

Liberation: https://github.com/dcs-liberation/dcs_liberation

Briefing Room: https://github.com/akaAgar/briefing-room-for-dcs

**Comment by pbzweihander** [comment]
I found a bug related to the geomagnetism reference time. I fixed it in the commit https://github.com/pbzweihander/peace-eye/commit/e6881186c171c90f84f3f530bc3da64bd3cbdf9f. I will release it immediately. Thank you for the issue!

**Comment by pbzweihander** [comment]
FYI: I reproduced the same issue using the Liberation.

**Comment by MrBlaze29** [comment]
That was fast. What a chad

**Comment by pbzweihander** [comment]
I released a new version, `v0.4.1`. Check it out and see if the issue resolves!

**Comment by MrBlaze29** [comment]
Checked and it's working now.
![image](https://github.com/pbzweihander/peace-eye/assets/81372082/542a112b-17a3-4cbb-9a52-c7361b2b947f)

Thanks
