### ISSUE TITLE
Doesnt login

### ISSUE THREAD

**Issue by thedragonkeeper** [pbzweihander/peace-eye#3]
unsure if youre still working on this but I got your latest release today and it doesnt login.
error produced is:

- Failed to connect: bad ACMI file type header, found:

It will constantly retry this and never connect

**Comment by pbzweihander** [comment]
HI! Thanks for the issue. What server did you try to connect? It would be helpful if I can reproduce the issue.

**Comment by thedragonkeeper** [comment]
The current version of tacview for DCS. Local.

**Comment by pbzweihander** [comment]
Make sure the Tacview realtime telemetry server is running. Were you able to connect with a normal Tacview client? peace-eye is kind of a Tacview realtime telemetry client. If a normal Tacview client is able to connect, peace-eye should work too.

**Comment by Dragonius** [comment]
I  have same problem as above.

Make sure the Tacview realtime telemetry server is running. YES
Were you able to connect with a normal Tacview client? YES

anyway to get logs of peace-eye

**Comment by pbzweihander** [comment]
hmm... What server did you trying to connect? May I reproduce it? I'll try to add more logs

**Comment by Dragonius** [comment]
own server, but can you expand 
src\acmi\mods.rs file and more debug as i dont know rust language.
Line number from 71 to 78
    // file type
    reader
        .read_line(&mut buf)
        .await
        .map_err(Error::AcmiReaderRead)?;
    if buf != "FileType=text/acmi/tacview\n" {
        return Err(Error::BadAcmiFileType(buf));
    }

**Comment by Dragonius** [comment]
https://www.tacview.net/documentation/acmi/en/

https://www.tacview.net/documentation/realtime/en/

**Comment by Dragonius** [comment]
i tested it without password and it works fine.

**Comment by Dragonius** [comment]
But with password, it fails.

**Comment by pbzweihander** [comment]
So it is a password problem. Thank you for the info! I'll try to fix it tomorrow

**Comment by pbzweihander** [comment]
I do not have much time to contribute to peace-eye, but I promise I'll fix it. May be this weekend?

**Comment by pbzweihander** [comment]
IT TOOK SO LONG TIME, but I managed to fix it!

Please try the new release 0.4.3 and let me know if the problem still exists.
